### ISSUE TITLE
Markup is broken in the jsonb statistic article

### ISSUE THREAD

**Issue by stof** [akorotkov/akorotkov.github.io#2]
In http://akorotkov.github.io/blog/2015/09/07/jsonb_statistics/, the markup is broken around the code snippet about storing values in keys:

![akorotkov_broken_markup](https://user-images.githubusercontent.com/439401/31707801-98c9a72a-b3ed-11e7-9c73-0473e391a67f.png)

It may be worth fixing it to make the post easier to read.

**Comment by akorotkov** [comment]
Hi!

Thank you for pointing!
I don't know why markdown parser started to behave differently than it did
before.
I've to fix that by moving code paragraph to another place.

------
Alexander Korotkov
Postgres Professional: http://www.postgrespro.com
The Russian Postgres Company

**Comment by stof** [comment]
Closing this as the fix is live

**Comment by akorotkov** [comment]
Good, thanks!
